Repository publiclab/PublicLab.Editor, pull requests merged in 2019-01, with the labels that each got.

#199 PL.Editor #181 Add data-url detection spec
  spec/javascripts/rich_text_module_spec.js
Labels: in progress

#200 PL.Editor #182 Data-urls detect-and-instruct
  dist/PublicLab.Editor.js
  src/modules/PublicLab.RichTextModule.js
Labels: in progress

#203 Adjust position of wk-commands respective to viewport
  dist/PublicLab.Editor.js
  src/modules/PublicLab.RichTextModule.js
Labels: in progress

#197 PL.Editor #126 Add AutoCenter ability for images and text
  dist/PublicLab.Editor.js
  src/adapters/PublicLab.Woofmark.js
  src/modules/PublicLab.RichTextModule.AutoCenter.js
  src/modules/PublicLab.RichTextModule.js
Labels: in progress

#206 Incorporate build in ci
  .travis.yml
Labels: in progress

#207 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: in progress

#226 Replace 'rake test' with 'grunt jasmine' in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready

#220 Add test for empty bold tags functionality
  spec/javascripts/rich_text_module_spec.js
Labels: ready

#233 Crescive issue232 patch: Added fix for unusual overlapping behavior
  dist/PublicLab.Editor.css
Labels: ready

#252 Fix Publish button disabled state
  dist/PublicLab.Editor.js
  examples/autocomplete.html
  examples/comment.html
  examples/errors.html
  examples/index.html
  examples/prepopulated.html
  examples/simple.html
  src/PublicLab.Editor.js
Labels: ready

#239 Added At.js support (removed Horsey and Banksy)
  .gitignore
  bower.json
  dist/PublicLab.Editor.js
  examples/data/atwho.PLE.js
  examples/data/emoji.js
  examples/index.html
  package-lock.json
  package.json
  src/adapters/PublicLab.Woofmark.js
  src/modules/PublicLab.RichTextModule.js
Labels: dependencies, enhancement, ready

#266 Minor markdown fix in CoC
  CODE_OF_CONDUCT.md
Labels: ready
